# 定义mysql的持久卷声明信息
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  # 存储类，具有相同存储类名称的pv和pvc才能进行绑定
  storageClassName: nfs
